[package]
name = "yomichan_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_json = "1.0.117"
thiserror = "1.0.61"
native_db = "0.7.1"
native_model = "0.4.19"
zip = "2.1.3"
tempfile = "3.10.1"
chrono = "0.4.38"
rayon = "1.10.0"
serde-untagged = "0.1.6"
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
snafu = "0.8.4"
bimap = { version = "0.6.3", features = ["std"] }
regex = "1.10.5"
unicode-segmentation = "1.11.0"
unicode-normalization = "0.1.23"
wana_kana = "3.0.0"
pretty_assertions = "1.4.1"
color-eyre = "0.6.3"
derive_more = { version = "1.0.0", features = ["debug"] }
indexmap = { version = "2.7.0", features = ["serde"] }

# https://www.reddit.com/r/rust/comments/gaeiwm/how_to_optionally_run_certain_tests/
[features]
default = []
rayon = []

# pprof is linux only
[target.'cfg(unix)'.dependencies]
pprof = { version = "0.13", features = ["flamegraph"] }

# compiles the test with --release
[profile.test]
inherits = "release"

# [net]
# git-fetch-with-cli = true
