[package]
name = "yomichan_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
serde_json = { version = "1.0.117" }
sqlx = { version = "0.7.4", features = [ "runtime-tokio" ] }
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0.61"
redb = "2.1.1"
bincode = "1.3.3"
zip = "2.1.3"
tempfile = "3.10.1"
chrono = "0.4.38"
rayon = "1.10.0"
serde-untagged = "0.1.6"

# pprof is linux only
[target.'cfg(unix)'.dependencies]
pprof = { version = "0.13", features = ["flamegraph"] }

# compiles the test with --release 
[profile.test]
inherits = "release"
